### ISSUE TITLE
ScrollDirection always PAUSED in Chrome on Windows

### ISSUE THREAD

**Issue by micru** [janpaepke/ScrollMagic#277] opened 2015-03-23 11:46 UTC
Hi Jan,

since the latest Chrome on Windows update, the scrollDirection property always seems to be PAUSED. It makes no difference weather i check the scrollDirection event property or accessing it via controller.info('scrollDirection'). It also does not matter which event type occurs. 

In Firefox this i no issue at all, and i had no chance to check other Browers or Chrome on Android and Mac.

You can inspect this e.g. in your debugging example. Whenever an event occurs containing a scrollDirection property, its always PAUSED in Chrome, but has correct states like FORWARD in Firefox
http://janpaepke.github.io/ScrollMagic/examples/basic/debugging.html

I am going to workaround this for now by keeping track of the scroll position manually.
But i think this is a major bug, at least for us.

Thanks for your help, and your really great work!!
Michael

**Comment by janpaepke** [comment] 2015-03-23 12:07
Hi Micru,

this issue is a duplicate of https://github.com/janpaepke/ScrollMagic/issues/271
Please use the search before posting. :)

This bug has been fixed in 2.0.2, which was released like 10 minutes ago...

**Closed by janpaepke** 2015-03-23 12:07 UTC
Labels: duplicate
