### ISSUE TITLE
Pin width 100% with container padding

### ISSUE THREAD

**Issue by justinmarsan** [janpaepke/ScrollMagic#252] opened 2015-03-02 16:54 UTC
I just ran into something that looks unexpected to me, not sure if this is what ScrollMagic is supposed to do or not.

* Create a `#container` of width 100% and 50px padding.
* Create a `#container > #block` of width 100%.
* Pin `#block` with `#container` as a triggerElement
* When `#block` gets pinned, it's width is set to 100% which takes up 100% of the viewport, minus 50px on the left, but not 50px on the right

Demo of the bug : http://demo.movingpages.io/scrollmagic/3-first-pin.html

In the inline style, `left` is set to `50px` which is correct, but `right` isn't set, so the block goes all the way to the right.

I'm guessing a solution to that would be to set the `right` value as well, instead of using `width` or use the computed px value as a `width`.

Is this the expected behavior or did I run into a bug ?

**Comment by krnlde** [comment] 2015-03-08 16:06
> but right isn't set, so the block goes all the way to the right.

Which browser do you use? I can't reproduce with Chrome 40.0.2214.111 Ubuntu 14.10 (64-bit) and FF 36.0

It has to use `left: 50px` because position is fixed once the pin triggers. at that moment the actual container is the body, which has no margin or padding. ScrollMagic simply copies the calculated dimensions it had before the pin. Since this was width: 100% (all block elements have that per default) and the parent's padding of 50px, ScrollMagic transformed these information to absolute values - in my case `left: 50px; width: 1153px;`, which equals a padding-right of 50px. Setting `right: 50px` is a bit more complex since the calculation of ScrollMagic uses simply the offset of the top left corner of your browser. 

Hope that helps.

**Comment by janpaepke** [comment] 2015-03-11 09:41
Sorry for the delayed answer, I was on holidays...
I'll look into this!

**Comment by justinmarsan** [comment] 2015-03-11 09:46
@krnlde Sorry, I didn't see the notification for your reply, my bad.

Here's how the block looks like before the pin : http://grab.by/FtB0 notice the 50px blank space on the right.

Here's how it looks like once the element gets pinned : http://grab.by/FtB8 50px blank space is gone, due to the width being set to 100% and right not being set.

I hope that helps !

**Comment by krnlde** [comment] 2015-03-11 10:06
Oh that's a big difference from what I see :) thanks for clarification!

**Comment by janpaepke** [comment] 2015-03-17 13:03
I took the liberty of converting your example into a fiddle so I could experiment on it:
http://jsfiddle.net/janpaepke/nppr3vLp/

unfortunately it seems to work as expected for me.
Before Pin:
![image](https://cloud.githubusercontent.com/assets/3076177/6687770/4d1173ae-ccae-11e4-8e59-9d4389d1ee20.png)

During Pin:
![image](https://cloud.githubusercontent.com/assets/3076177/6687778/57a6d55c-ccae-11e4-9f7b-b83f90b8a3f3.png)

Please clarify how to reproduce...

**Comment by justinmarsan** [comment] 2015-03-17 15:04
I checked your pin, like I said, the issue still appears from me.

apparently you see the bug when using an external mouse but not when using a trackpad (or is it the opposite ?).

Either way I'm not sure I understand the benefit of having `right` set to àuto` and `width: 100%` for a pin, wouldn't it make as much sense to define right based on the actual "right" of the box anyway ? That should fix the issue too I think, right ?

**Closed** 2015-03-17 15:54 UTC
Labels: potential bug
