### ISSUE TITLE
Animations complete on load in Chrome/ iOS

### ISSUE THREAD

**Issue by rsancho** [janpaepke/ScrollMagic#290] opened 2015-04-08 18:05 UTC
Hello janpaepke!

I wanted to tell you first off that your plugin is incredibly amazing - thank you for creating it.

Secondly, I am having a small issue with a page, only in Chrome browser in iOS. Basically, when the page loads, it loads in a state that reflects the static end points of all animations on the page.

In other words, all animations are complete on load.

I'm hoping you can help shed some light on the subject, any help would be very much appreciated. Here is the page, running a-ok on all browsers with the exception of Chrome web browser in iOS:

http://www.mtv.com/news/interactive/kendrick-lamar-butterfly-lyrics-meaning/

and here is the .js include:
http://www.mtv.com/content/news/2015/kendrick/js/kendrick.js

If you need any other resources for clarification (screenshots, source-code), please let me know - and thanks in advance!

- Rich

**Comment by janpaepke** [comment] 2015-04-09 14:00
Hi Rich, glad you like the plugin.
I'll try to look into this soon.

**Comment by rsancho** [comment] 2015-04-09 14:30
Thank you, Jan - much appreciated!



On Apr 9, 2015, at 10:01 AM, Jan Paepke <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Rich, glad you like the plugin.
I'll try to look into this soon.

**Comment by janpaepke** [comment] 2015-04-13 10:04
So I checked it out and can confirm this behavior.
It's really curious, especially as it works fine in mobile safari.

The problem is, that as far as I know there's no remote debugging for chrome on ios (as for safari).
So you'd have to do some experiments to try to find out what's causing this.
Also I'm afraid all I can offer is guesswork...

My best guess is that there's one of two possible things happening:
 1. There's a js error somewhere in the code, that causes all the scene additions to fail and the animations to run. So they run without ever being added to their respective scenes.
 2. The positions of the trigger elements are off for some reason, causing the scenes to be triggered earlier than anticipated.

Here's what you could try:
 - Use your console to make sure there are no errors in your code (i.e. the 'scene is not defined' error in line 552). Also note, that `pushFollowers` is an option for `setPin` not for the scene.
 - Try adding only one scene, comment out the rest and see if it works. If it does incrementally add the next one and try to figure out which one is the one that breaks it.
 - Try echoing out the offsets of the trigger elements and see if they match in all browsers.


let us know if you find anything...

**Comment by janpaepke** [comment] 2015-04-29 12:02
hi there! are there any updates?

**Comment by rsancho** [comment] 2015-04-29 14:12
Hi janpaepke,

Thank you for your detailed reply a few weeks ago - I have yet to dive into troubleshooting the page, but it's on my list!

**Comment by janpaepke** [comment] 2015-05-07 11:54
closing this until further updates are available.

**Closed by janpaepke** 2015-05-07 11:54 UTC
Labels: potential bug, support
