### ISSUE TITLE
Safari (mac) animations are not smooth 

### ISSUE THREAD

**Issue by klojniewski** [janpaepke/ScrollMagic#247] opened 2015-02-24 14:24 UTC
Hello!

I have problem with animation on Safari.
It works much better on Google Chrome and I dont know why.

Below video describing the problem:
http://screencast.com/t/tXZawZkt2h7
Left: Google Chrome  Right: Safarii 

Bug is visible on all versions of Safarii (tested on diffrent computers and browsers).

Do you have any ideas?

Best,
Chris

**Comment by krnlde** [comment] 2015-02-24 15:13
Possible duplicate of #218 #186 #167

**Comment by janpaepke** [comment] 2015-03-11 09:18
Hi Chris!
Sorry for the delayed answer, I was on holidays...

I suspect that this is due to unnecessary repaints and overall browser performance.
Are you tweening the `transformY` (just `y` in GSAP) or `top` parameter for the elements?
Transform is far better...
For more details watch this awesome explanation by @paulirish: https://www.youtube.com/watch?v=R6TXuXV1bbY

**Comment by janpaepke** [comment] 2015-03-17 12:43
Closing this in favor of https://github.com/janpaepke/ScrollMagic/issues/256
Confirmed bug in Safari...

**Closed by janpaepke** 2015-03-17 12:43 UTC
Labels: potential bug, question
